--TÌNH HUỐNG 1: DIRTY READ			- HIẾU
--T1: CHỨC NĂNG THÊM HỢP ĐỒNG THUÊ (NHÂN VIÊN)
--T2:CHỨC NĂNG XEM DANH SÁCH HỢP ĐỒNG (QUẢN LÝ) --> READ COMMITTED
CREATE PROCEDURE USP_X_SELECT_CONTRACT
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL READ COMMITTED
	BEGIN TRAN
	SELECT * FROM DBO.CONTRACT
	COMMIT TRAN
END
GO

EXEC USP_X_SELECT_CONTRACT
GO


--TÌNH HUỐNG 2: LOST UPDATE			- HIẾU
--T1 & T2: CHỨC NĂNG TĂNG GIÁ THUÊ NHÀ --> REPEATABLE READ
--USP_CONVER_INCREASE_RENT


--TÌNH HUỐNG 3: DIRTY READ			- Q HUY
--T1: CHỨC NĂNG THÊM LỊCH XEM (NHÂN VIÊN)
--T2: CHỨC NĂNG XEM LỊCH XEM NHÀ (KHÁCH HÀNG) --> READ COMMITTED
CREATE PROCEDURE USP_X_SELECT_VIEWINFO @CUSID CHAR(5)
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL READ COMMITTED
	BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DBO.CUSTOMER WHERE CUSTOMERID = @CUSID)
	BEGIN
		PRINT N'THÔNG TIN KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
	
	SELECT * FROM DBO.VIEWINFO WHERE VCUSTOMERID = @CUSID
	COMMIT TRAN
END
GO

--EXEC USP_SELECT_VIEWINFO 'C0003'
--GO
--EXEC USP_X_SELECT_VIEWINFO 'C0003'
--GO

--TÌNH HUỐNG 4: UNREPEATABLE READ	- Q HUY
--T2: CẬP NHẬT THÔNG TIN CÁ NHÂN
--T1: CHỨC NĂNG TÌM NHÂN VIÊN THEO KHU VỰC (QUẢN LÝ) --> REPEATABLE READ 
CREATE PROCEDURE USP_X_SELECT_EMP_AREA @AREA NVARCHAR(50), @NUMRESULT INT OUT
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL REPEATABLE READ 
	BEGIN TRAN
	SELECT @NUMRESULT = COUNT(*) FROM DBO.EMPLOYEE WHERE EMPLOYEEADDRESS LIKE @AREA + '%'
	IF(@NUMRESULT = 0)
	BEGIN
		PRINT N'KHÔNG TÌM THẤY KẾT QUẢ NÀO'
		ROLLBACK TRAN
		RETURN
	END
	ELSE
	BEGIN
		PRINT N'SỐ KẾT QUẢ TÌM THẤY: ' + CAST(@NUMRESULT AS CHAR(10))
	END

	WAITFOR DELAY '00:00:05'
	
	SELECT * FROM DBO.EMPLOYEE WHERE EMPLOYEEADDRESS LIKE @AREA + '%'
	COMMIT TRAN
END
GO

--EXEC USP_X_SELECT_EMP_AREA N'Thủ Đức', 0
--GO

--T2: CẬP NHẬT THÔNG TIN CÁ NHÂN

--EXEC USP_X_UPDATE_EMP_AREA 'E0001', N'Quận 2'
--SELECT * FROM DBO.EMPLOYEE WHERE EMPLOYEEID = 'E0001'

--TÌNH HUỐNG 5: LOST UPDATE			- H HUY
--T1 & T2: CHỨC NĂNG THÊM LỊCH XEM (NHÂN VIÊN, QUẢN LÝ) --> REPEATABLE READ
	--SELECT HOMEID, HVIEW FROM DBO.HOME
	--EXEC USP_INSERT_VIEWINFO 'C0013', 'H0012', '2020-12-07', ''
	--SELECT HOMEID, HVIEW FROM DBO.HOME

--TÌNH HUỐNG 6: CONVERSION DEADLOCK			- H HUY
--T1 & T2: CHỨC NĂNG THÊM LỊCH XEM (NHÂN VIÊN, QUẢN LÝ)
CREATE PROCEDURE USP_X_INSERT_VIEWINFO @CUSID CHAR(5), @HOMEID CHAR(5), @DATE DATETIME, @CMT NVARCHAR(100)
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL READ COMMITTED
	BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DBO.CUSTOMER WHERE CUSTOMERID = @CUSID)
	OR NOT EXISTS(SELECT * FROM DBO.HOME WHERE HOMEID = @HOMEID)
	BEGIN
		PRINT N'THÔNG TIN KHÔNG HỢP LỆ'
		ROLLBACK TRAN
		RETURN
	END
	DECLARE @NUM INT = (SELECT HVIEW 
	FROM DBO.HOME WITH (UPDLOCK)
	WHERE HOMEID = @HOMEID)
	INSERT INTO DBO.VIEWINFO ( VCUSTOMERID, VHOMEID, VIEWDATE, CUSTOMERCOMMENT)
	VALUES (@CUSID, @HOMEID, @DATE, @CMT)

	WAITFOR DELAY '00:00:05'

	IF ((@@ERROR <> 0) OR (NOT EXISTS (SELECT * FROM DBO.CUSTOMER C, DBO.REQUEST R, DBO.HOME H, DBO.VIEWINFO V 
	WHERE V.VCUSTOMERID = @CUSID AND V.VHOMEID = @HOMEID AND V.VIEWDATE = @DATE AND V.VCUSTOMERID = C.CUSTOMERID 
	AND C.CUSTOMERID = R.RCUSTOMERID AND V.VHOMEID = H.HOMEID AND H.HOMETYPEID = R.RHOMETYPEID)))
	BEGIN
		PRINT N'THÊM LỊCH XEM THẤT BẠI'
		ROLLBACK TRAN
		RETURN
	END
	PRINT N'THÊM LỊCH XEM THÀNH CÔNG'

	SET @NUM = @NUM + 1;
	UPDATE DBO.HOME
	SET HVIEW = @NUM
	WHERE HOMEID = @HOMEID

	COMMIT TRAN 
END
GO

--TÌNH HUỐNG 7: PHANTOM				- H HUY
--T1: CHỨC NĂNG THỐNG KÊ SỐ HỢP ĐỒNG MỖI NHÂN VIÊN --> SERIALIZABLE
CREATE PROCEDURE USP_X_COUNT_CONTRACT @TOTAL INT OUT
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL SERIALIZABLE 
	BEGIN TRAN
	SELECT @TOTAL = COUNT(*) FROM DBO.CONTRACT
	PRINT N'TỔNG SỐ HỢP ĐỒNG: ' + CAST(@TOTAL AS CHAR(10))

	WAITFOR DELAY '00:00:05'

	SELECT E.EMPLOYEEID, E.EMPLOYEENAME, COUNT(E.EMPLOYEEID) 'AMOUNT CONTRACT'
	FROM DBO.EMPLOYEE E, DBO.CONTRACT C, DBO.HOME H
	WHERE (C.CHOMEID = H.HOMEID AND H.HEMPLOYEEID = E.EMPLOYEEID)
	GROUP BY E.EMPLOYEEID, E.EMPLOYEENAME
	UNION 
	SELECT EMPLOYEEID, EMPLOYEENAME, 0 'AMOUNT CONTRACT'
	FROM DBO.EMPLOYEE
	WHERE EMPLOYEEID NOT IN (SELECT E.EMPLOYEEID
	FROM DBO.EMPLOYEE E, DBO.CONTRACT C, DBO.HOME H
	WHERE (C.CHOMEID = H.HOMEID AND H.HEMPLOYEEID = E.EMPLOYEEID))

	COMMIT TRAN
END
GO

EXEC USP_X_COUNT_CONTRACT 0
GO

--TÌNH HUỐNG 8: UNREPEATABLE READ	- H HUY
--T1: CHỨC NĂNG TÌM NHÀ BÁN/THUÊ THEO KHU VỰC (KHÁCH HÀNG) --> REPEATABLE READ 
CREATE PROCEDURE USP_X_SELECT_HOME_AREA @AREA NVARCHAR(50), @TYPE NVARCHAR(50), @NUMRESULT INT OUT
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL REPEATABLE READ 
	BEGIN TRAN
	DECLARE @TYPEID CHAR(5)
	SELECT @TYPEID = TYPEID FROM DBO.TYPE WHERE @TYPE = TYPENAME

	SELECT @NUMRESULT = COUNT(*) FROM DBO.HOME WHERE HADDRESSDISTRICT = @AREA  AND HOMETYPEID = @TYPEID
	IF(@NUMRESULT = 0)
	BEGIN
		PRINT N'KHÔNG TÌM THẤY KẾT QUẢ NÀO'
		ROLLBACK TRAN
		RETURN
	END
	ELSE
	BEGIN
		PRINT N'SỐ KẾT QUẢ TÌM THẤY: ' + CAST(@NUMRESULT AS CHAR(10))
	END

	WAITFOR DELAY '00:00:05'
	
	SELECT * FROM DBO.HOME WHERE HADDRESSDISTRICT = @AREA AND HOMETYPEID = @TYPEID
	COMMIT TRAN
END
GO

--EXEC USP_SELECT_HOME_AREA N'Quận 5', N'Nhà thuê', 0
--GO
--INSERT [HOME] ([HOMEID], [HHOSTID], [HEMPLOYEEID], [HADDRESSSTREET], [HADDRESSDISTRICT], [HADDRESSSCITY], [HOMESTATUSID], [HOMETYPEID], [ROOMNUMBER], [POSTDATE], [EXPIRATIONDATE], [HVIEW]) VALUES (N'H0020', N'F0002', N'E0005', N'456 Trí Quang', N'Quận 7', N'Tp Hồ Chí Minh', N'S03  ', N'T02  ', 3, CAST(N'2020-12-30T22:50:29.023' AS DateTime), CAST(N'2023-05-01' AS Date), 0)
--INSERT [HOMESELL] ([HOMESELLID], [PRICE], [HOSTREQUEST]) VALUES (N'H0020', 3510000000.0000, N'Không')

--TÌNH HUỐNG 10:DIRTY READ			- HUYỀN
--T1: CHỨC NĂNG THÊM NHÀ THUÊ (NHÂN VIÊN)
--T2: CHỨC NĂNG XEM DANH SÁCH NHÀ (KHÁCH HÀNG) --> READ COMMITTED
CREATE PROCEDURE USP_X_SELECT_HOME @TYPE NVARCHAR(50)
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL READ COMMITTED
	BEGIN TRAN

	DECLARE @STT CHAR(5)
	SELECT @STT = STATUSID FROM DBO.STATUS WHERE STATUSNAME = N'Còn trống'
	DECLARE @TYPEID CHAR(5)
	SELECT @TYPEID = TYPEID FROM DBO.TYPE WHERE TYPENAME = @TYPE

	SELECT HOMEID, HADDRESSDISTRICT, ROOMNUMBER, POSTDATE, HVIEW, RENT FROM DBO.HOME, DBO.HOMERENT
	WHERE HOMEID = HOMERENTID AND HOMETYPEID = @TYPEID AND HOMESTATUSID = @STT

	COMMIT TRAN
END
GO


--TÌNH HUỐNG 11:PHANTOM				- HUYỀN
--T2:THÊM NHÀ BÁN (NHÂN VIÊN)
--T1:TÌM NHÀ THEO KHU VỰC (KHÁCH HÀNG)  --> SERIALIZABLE
CREATE PROCEDURE USP_XX_SELECT_HOME_AREA @AREA NVARCHAR(50), @TYPE NVARCHAR(50), @NUMRESULT INT OUT
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL SERIALIZABLE
	BEGIN TRAN
	DECLARE @TYPEID CHAR(5)
	SELECT @TYPEID = TYPEID FROM DBO.TYPE WHERE @TYPE = TYPENAME

	SELECT @NUMRESULT = COUNT(*) FROM DBO.HOME WHERE HADDRESSDISTRICT = @AREA  AND HOMETYPEID = @TYPEID
	IF(@NUMRESULT = 0)
	BEGIN
		PRINT N'KHÔNG TÌM THẤY KẾT QUẢ NÀO'
		ROLLBACK TRAN
		RETURN
	END
	ELSE
	BEGIN
		PRINT N'SỐ KẾT QUẢ TÌM THẤY: ' + CAST(@NUMRESULT AS CHAR(10))
	END

	WAITFOR DELAY '00:00:05'
	
	SELECT * FROM DBO.HOME WHERE HADDRESSDISTRICT = @AREA AND HOMETYPEID = @TYPEID
	COMMIT TRAN
END
GO

--TÌNH HUỐNG 12:DEADLOCK_CONVER		- KHOA
--T1 & T2: CHỨC NĂNG TĂNG GIÁ THUÊ NHÀ --> WITH (UPDLOCK)
CREATE PROCEDURE USP_X_INCREASE_RENT @ID CHAR(5), @ADD MONEY
AS
BEGIN
	SET TRANSACTION ISOLATION
	LEVEL READ COMMITTED
	BEGIN TRAN

	IF NOT EXISTS(SELECT * FROM DBO.HOMERENT WHERE HOMERENTID = @ID)
	BEGIN
		PRINT N'NHÀ KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN
	END

	DECLARE @RENT MONEY 
	SELECT @RENT = RENT 
	FROM DBO.HOMERENT WITH(UPDLOCK)
	WHERE HOMERENTID = @ID

	WAITFOR DELAY '00:00:05'

	SET @RENT = @RENT + @ADD
	UPDATE DBO.HOMERENT
	SET RENT = @RENT
	WHERE HOMERENTID = @ID
	PRINT N'CẬP NHẬT THÀNH CÔNG'

	COMMIT TRAN
END
GO

